export const REQUEST_PHOTOS_PENDING = 'REQUEST_PHOTOS_PENDING';
export const REQUEST_PHOTOS_SUCCESS = 'REQUEST_PHOTOS_SUCCESS';
export const REQUEST_PHOTOS_FAILED = 'REQUEST_PHOTOS_FAILED';
export const TOGGLE_PHOTO_MODAL = 'TOGGLE_PHOTO_MODAL';
export const TOGGLE_CAROUSEL_MODAL = 'TOGGLE_CAROUSEL_MODAL';
